version: "3.8"

services:
  domserver:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    restart: always
    privileged: true
    hostname: domserver
    container_name: domserver
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
      - ./redis/php.ini:/usr/local/etc/php/php.ini
      - ./redis/framework.yaml:/opt/domjudge/domserver/webapp/config/packages/framework.yaml
      - ./redis/services.yaml:/opt/domjudge/domserver/webapp/config/services.yaml
      - ./template-overrides/base.html.twig:/opt/domjudge/domserver/webapp/templates/team/base.html.twig
      - ./template-overrides/submit_scripts.html.twig:/opt/domjudge/domserver/webapp/templates/team/partials/submit_scripts.html.twig
      - ./problem-id/JudgeTask.php:/opt/domjudge/domserver/webapp/src/Entity/JudgeTask.php
      - ./problem-id/JudgehostController.php:/opt/domjudge/domserver/webapp/src/Controller/API/JudgehostController.php
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
      FPM_MAX_CHILDREN: 40
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https
      - traefik.http.routers.domserver-http.rule=Host(`${SITES}`)
      - traefik.http.routers.domserver-http.entrypoints=http
      - traefik.http.routers.domserver-http.middlewares=prod-redirect
      - traefik.http.routers.domserver-https.rule=Host(`${SITES}`)
      - traefik.http.routers.domserver-https.entrypoints=https
      - traefik.http.routers.domserver-https.tls=true
      - traefik.http.routers.domserver-https.tls.certresolver=le
      - traefik.http.services.domserver.loadbalancer.server.port=80
    networks:
      - traefik-public
      - mariadb-network
      - web-network

  domserver-judge-1:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    restart: always
    privileged: true
    hostname: domserver-judge
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    labels:
      - traefik.enable=false
    networks:
      - mariadb-network
      - web-network
      - judge-network

volumes:
  submissions-data:
    name: domserver-submissions-data
  judgings-data:
    name: domserver-judgings-data

networks:
  mariadb-network:
    name: mariadb-network
    external: true
  web-network:
    name: web-network
  traefik-public:
    name: traefik-public
    external: true
  judge-network:
    name: judge-network
