services:
  judgehost-1:
    image: domjudge/judgehost:8.2.3
    restart: always
    privileged: true
    hostname: judgehost-1
    container_name: judgehost
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup      
      - ./problem-id/judgedaemon.main.php:/opt/domjudge/judgehost/lib/judge/judgedaemon.main.php
      - ./problem-id/compile.sh:/opt/domjudge/judgehost/lib/judge/compile.sh
      - ./problem-id/testcase_run.sh:/opt/domjudge/judgehost/lib/judge/testcase_run.sh
    environment:      
      DAEMON_ID: "1"
      DOMSERVER_BASEURL: http://${DOMSERVER_MAIN_IP}/
      JUDGEDAEMON_PASSWORD: ${JUDGEHOST_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    networks:
      - mariadb-network
      - web-network

  judgehost-2:
    image: domjudge/judgehost:8.2.3
    restart: always
    privileged: true
    hostname: judgehost-2
    container_name: judgehost-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup      
      - ./problem-id/judgedaemon.main.php:/opt/domjudge/judgehost/lib/judge/judgedaemon.main.php
      - ./problem-id/compile.sh:/opt/domjudge/judgehost/lib/judge/compile.sh
      - ./problem-id/testcase_run.sh:/opt/domjudge/judgehost/lib/judge/testcase_run.sh
    environment:      
      DAEMON_ID: "2"
      DOMSERVER_BASEURL: http://${DOMSERVER_MAIN_IP}/
      JUDGEDAEMON_PASSWORD: ${JUDGEHOST_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    networks:
      - mariadb-network
      - web-network

  judgehost-3:
    image: domjudge/judgehost:8.2.3
    restart: always
    privileged: true
    hostname: judgehost-3
    container_name: judgehost-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup      
      - ./problem-id/judgedaemon.main.php:/opt/domjudge/judgehost/lib/judge/judgedaemon.main.php
      - ./problem-id/compile.sh:/opt/domjudge/judgehost/lib/judge/compile.sh
      - ./problem-id/testcase_run.sh:/opt/domjudge/judgehost/lib/judge/testcase_run.sh
    environment:      
      DAEMON_ID: "3"
      DOMSERVER_BASEURL: http://${DOMSERVER_MAIN_IP}/
      JUDGEDAEMON_PASSWORD: ${JUDGEHOST_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    networks:
      - mariadb-network
      - web-network

networks:
  mariadb-network:
    name: mariadb-network
    external: true
  web-network:
    name: web-network
    external: true
